d435_aligned_source:
  ros__parameters:
    is_physical: true
    distance_scale: 1.0
    frame_id: aligned_camera_optical_frame
    publish_rate: 10.0
    fx: 455.20
    fy: 459.43
    cx: 308.53
    cy: 213.56

semantic_yolo_detector:
  ros__parameters:
    confidence: 0.30
    class_filter: "2,9,11"
    device: cpu # this has to be changed and configured for qcar2, since the docker 
    #image for qcar2 Has support for gpu in physical model.

object_3d_estimator:
  ros__parameters:
    min_depth: 0.05
    max_depth: 4.0
    depth_crop_ratio: 0.5

#for QCar2 physical version. we have to probably make more adjustements.
